---- USER
--
--DROP TABLE IF EXISTS `user`;
--CREATE TABLE IF NOT EXISTS `user` (
--  `user_id` int(11) NOT NULL,
--  `active` bit(1) DEFAULT NULL,
--  `code_postal` varchar(255) NOT NULL,
--  `commune` varchar(255) NOT NULL,
--  `email` varchar(255) NOT NULL,
--  `last_name` varchar(255) NOT NULL,
--  `name` varchar(255) NOT NULL,
--  `niveau` varchar(255) DEFAULT NULL,
--  `password` varchar(255) NOT NULL,
--  `voie` varchar(255) NOT NULL,
--  PRIMARY KEY (`user_id`),
--  UNIQUE KEY `UK_ob8kqyqqgmefl0aco34akdtpe` (`email`)
--) ENGINE=MyISAM DEFAULT CHARSET=utf8;
--
--INSERT INTO `user` (`user_id`, `active`, `code_postal`, `commune`, `email`, `last_name`, `name`, `niveau`, `password`, `voie`) VALUES (2, true, '75000', 'Paris', 'admin@admin.com', 'min', 'ad', '5c', '$2a$10$FVyWRBbaGu8fwFzYAqo5mOWh7rVnS7PYI4M1P7Tq645l/fxf4PJUa', '42 rue de l admin'),
--(9, TRUE, '75000', 'Paris', 'francois@gmail.com', 'Pignon', 'François', '5a', '$2a$10$bDhGuv698Gh72czX79Qx1O5C8Yi7Ng4MyZitnqxLzvxCL8p.r6P36', '31 rue de la colombre'),
--(5, TRUE, '69000', 'Lyon', 'cerise@gmail.com', 'Cerisier', 'Cerise', '2', '$2a$10$FFPLu93JG64qoxjCHTUl5unbU.kk1zp/egI4BVZ4ZpLpwh2gVifOO', '1 rue du cerisier');
--
---- ROLE
--
--DROP TABLE IF EXISTS `role`;
--CREATE TABLE IF NOT EXISTS `role` (
--  `role_id` int(11) NOT NULL,
--  `role` varchar(255) DEFAULT NULL,
--  PRIMARY KEY (`role_id`)
--) ENGINE=MyISAM DEFAULT CHARSET=utf8;
--
--INSERT INTO `role` (`role_id`, `role`) VALUES (3, 'ADMIN'),
--(6, 'UTILISATEURCONNECTE'),
--(10, 'UTILISATEURCONNECTE');
--
--
--
----INSERT INTO `user_role` (`user_id`, `role_id`) VALUES (1, 3);
----(5, 6),
----(9, 10)
--
--
----TOPO
--
--DROP TABLE IF EXISTS `topo`;
--CREATE TABLE IF NOT EXISTS `topo` (
--  `topo_id` bigint(20) NOT NULL AUTO_INCREMENT,
--  `nom` varchar(255) DEFAULT NULL,
--  `region` varchar(255) DEFAULT NULL,
--  `user_id` int(11) NOT NULL,
--  `date` datetime DEFAULT NULL,
--  `disponible` bit(1) NOT NULL,
--  `description` varchar(255) DEFAULT NULL,
--  PRIMARY KEY (`topo_id`),
--  KEY `FKpurggp4l82two9ekgr11hx2qk` (`user_id`)
--) ENGINE=MyISAM AUTO_INCREMENT=7 DEFAULT CHARSET=utf8;
--
--INSERT INTO `topo` (`topo_id`, `nom`, `region`, `user_id`, `date`, `disponible`, `description`) VALUES (1, 'Super topo', 'Centre', 1, '2021-04-20 00:00:00', FALSE, 'Il regroupe pas mal de site'),
--(2, 'grimpette', 'Anjou', 5, '2020-07-15 00:00:00', FALSE, 'ça monte dur'),
--(3, 'Le topo de francois', 'Alsace', 9, '2021-04-07 00:00:00', FALSE, 'il est vraiment complet'),
--(5, 'test2', 'Centre', 1, '2009-02-02 00:00:00', FALSE, 'ertfdfc'),
--(6, 'derniertest', 'Bretagne', 1, '2017-03-25 00:00:00', FALSE, 'vraiment le dernier?');
--
---- RESERVATION
--
--DROP TABLE IF EXISTS `reservation`;
--CREATE TABLE IF NOT EXISTS `reservation` (
--  `id` bigint(20) NOT NULL AUTO_INCREMENT,
--  `demande_reservation` bit(1) DEFAULT NULL,
--  `reserve` bit(1) DEFAULT NULL,
--  `valider_reservation` bit(1) DEFAULT NULL,
--  `topo_id` bigint(20) NOT NULL,
--  `user_id_demande` int(11) NOT NULL,
--  PRIMARY KEY (`id`),
--  KEY `FKs6rhp8bjbn9p9imq1k5fcpb6a` (`topo_id`),
--  KEY `FKos39dukqhe36qsfj4x69hsctt` (`user_id_demande`)
--) ENGINE=MyISAM AUTO_INCREMENT=8 DEFAULT CHARSET=utf8;
--
--INSERT INTO `reservation` (`id`, `demande_reservation`, `reserve`, `valider_reservation`, `topo_id`, `user_id_demande`) VALUES (3, FALSE, TRUE, TRUE, 1, 5),
--(2, FALSE, FALSE, FALSE, 2, 1);
--
----SITE
--
--DROP TABLE IF EXISTS `site`;
--CREATE TABLE IF NOT EXISTS `site` (
--  `id` bigint(20) NOT NULL AUTO_INCREMENT,
--  `cotation_max` varchar(255) DEFAULT NULL,
--  `cotation_min` varchar(255) DEFAULT NULL,
--  `description` varchar(500) DEFAULT NULL,
--  `nb_voies` int(11) NOT NULL,
--  `nom` varchar(255) DEFAULT NULL,
--  `region` varchar(255) DEFAULT NULL,
--  `site_image` varchar(255) DEFAULT NULL,
--  `certifie` bit(1) NOT NULL,
--  `nb_secteurs` int(11) NOT NULL,
--  PRIMARY KEY (`id`)
--) ENGINE=MyISAM AUTO_INCREMENT=6 DEFAULT CHARSET=utf8;
--
--INSERT INTO `site` (`id`, `cotation_max`, `cotation_min`, `description`, `nb_voies`, `nom`, `region`, `site_image`, `certifie`, `nb_secteurs`) VALUES (1, '8b+', '3a', 'Toujours aussi spectaculaire et merveilleux', 126, 'Le Peyssin', 'Alpes', 'LePeyssin.jpg', TRUE, 53),
--(2, '7b+', '3a', 'Ce site n est pas de tout repos mais il en vaut la chandelle comme on dit, une expositions plein sud de la plupart des parois font que la luminosité y est splendide et ce toute la journée. N oubliez pas votre crème solaire', 115, 'Balme Yenne', 'Alpes', 'BalmeYenne.jpg', FALSE, 47),
--(3, '6b+', '3', 'Pour découvrir l escalade en famille ou entre amis, rien de tel que le si de l Autoire', 87, 'Autoire', 'Centre', 'Autoire.jpg', FALSE, 24);
--
---- COMMENTAIRE
--
--DROP TABLE IF EXISTS `commentaire`;
--CREATE TABLE IF NOT EXISTS `commentaire` (
--  `commentaire_id` bigint(20) NOT NULL,
--  `com` varchar(500) DEFAULT NULL,
--  `com_date` datetime DEFAULT NULL,
--  `site_id` bigint(20) NOT NULL,
--  `user_id` int(11) NOT NULL,
--  PRIMARY KEY (`commentaire_id`),
--  KEY `FK7poewyx0vupiexwj3o3v5r746` (`site_id`),
--  KEY `FKnxdc2ad1nq0dstrheq6tmsoo6` (`user_id`)
--) ENGINE=MyISAM DEFAULT CHARSET=utf8;
--
--INSERT INTO `commentaire` (`commentaire_id`, `com`, `com_date`, `site_id`, `user_id`) VALUES (3, 'Que de souvenirs sur ce site', '2021-04-18 20:41:55', 1, 1),
--(7, 'pourquoi pas !ff', '2021-04-18 20:50:08', 2, 5),
--(8, 'oui on s\'est bien amusé', '2021-04-18 20:50:30', 1, 5);
--
